adventure tools: add help and error handling

diff --git a/tools/adiff b/tools/adiff
--- a/tools/adiff
+++ b/tools/adiff
@@ -6,11 +6,11 @@
 #
 # usage:
 #
-# adiff -h|--help [--last|--fin|--version VERSION] FILE
+# adiff -h|--help [--last|--fin|--version VERSION] [FILE]
 
 parse() {
   local sn=1
-  echo "$@"
+  # echo "$@"
 
   while [[ $# -gt 0 ]]; do
     case "$1" in
@@ -22,7 +22,7 @@ parse() {
         [[ -z "${file}" ]] && file="$1"
                                                            ;;
     esac
-    echo $# "${@}"
+    # echo $# "${@}"
     shift $sn
     sn=1
   done
@@ -59,20 +59,22 @@ usage() {
 
    usage:
 
-   adiff [--last|--fin|--version VERSION] FILE
-   adiff -h|--help
+     adiff [--last|--fin|--version VERSION] [FILE]
+     adiff -h|--help
 EOF
 }
 
 help() {
   usage
   cat <<EOF
+
      -l,--last      diff the last version of this FILE
      -f,--fin       diff the final version of this FILE
      -v,--version   diff the specific version VERSION of FILE
      -h,--help      print this help
      FILE           which file to generate the diff for
                     adventure|test[_game]
+                    (default: adventure)
 EOF
 }
 
@@ -93,10 +95,12 @@ main() {
     help)     help ; exit   ;;
   esac
 
-  if [[ ! -f "${srcdir}/${diff_file}" ]]; then
-    echo "file not found: ${diff_file}"
-    exit 1
-  fi
+  for f in "${diff_file}" "${current}"; do
+    if [[ ! -f "${srcdir}/${f}" ]]; then
+      echo "file not found: ${f}"
+      exit 1
+    fi
+  done
 
   vimdiff "${srcdir}/${diff_file}" "${srcdir}/${current}"
 }
diff --git a/tools/lnk b/tools/lnk
--- a/tools/lnk
+++ b/tools/lnk
@@ -3,16 +3,46 @@
 # create a symbolic link to a particular version of the adventure
 # game and test file if it exists
 #
+# usage: lnk VERSION
+#
+
+setopt nullglob
+setopt extendedglob
 
 rootdir="$(cd "${0%/*}/.." && pwd -P)"
 
-main() {
-  local version="$1" srcdir="${rootdir}/pythonclass/adventure" name file
+usage() {
+  cat <<EOF
+lnk -- create a symbolic link to a particular version of the adventure
+       game and test file if it exists
 
-  for name in adventure test_game; do
+usage: lnk VERSION
+
+EOF
+}
+
+main() {
+  local version="$1" srcdir="${rootdir}/pythonclass/adventure" ec=0 mode name files file
+
+  [[ $# -ne 1 ]] && mode=usage ec=1
+  [[ "$*" =~ (-h|--help) ]] && mode=usage
+
+  if [[ "$mode" == "usage" ]]; then
+    usage
+    exit $ec
+  fi
+
+  files=( ${srcdir}/*-${version}.py )
+
+  if [[ ${#files} -eq 0 ]]; then
+    echo "Error: No files found for version '${version}'"
+    exit 1
+  fi
+
+  for file in adventure test_game; do
     file="${srcdir}/${name}-${version}.py"
     if [[ -f "$file" ]] ; then
-      ln -sf "${file}" "${rootdir}/${name}.py"
+      ln -vsf "${file}" "${rootdir}/${name}.py"
     fi
   done
 
